import { describe, it, expect, beforeEach, vi } from 'vitest';
import { mount } from '@vue/test-utils';
import { createPinia, setActivePinia } from 'pinia';
import { Quasar } from 'quasar';
import BingoGenerator from './BingoGenerator.vue';
import BingoCard75 from './BingoCard75.vue';
import BingoCard90 from './BingoCard90.vue';
import { BingoTypes } from '../models/BingoCard';
import type { Bingo75Card } from '../models/Bingo75Card';
import type { Bingo90Card } from '../models/Bingo90Card';

// Type helper para el componente BingoGenerator
interface BingoGeneratorVM {
  gameType: BingoTypes;
  quantity: number;
  generate: () => void;
  printCards: () => void;
  store: { cards75: Bingo75Card[]; cards90: Bingo90Card[] };
}

describe('BingoGenerator.vue', () => {
  beforeEach(() => {
    setActivePinia(createPinia());
  });

  const mountComponent = () => {
    return mount(BingoGenerator, {
      global: {
        plugins: [Quasar],
        components: {
          BingoCard75,
          BingoCard90,
        },
      },
    });
  };

  it('should render the component', () => {
    const wrapper = mountComponent();
    expect(wrapper.exists()).toBe(true);
  });

  it('should have game type selector', () => {
    const wrapper = mountComponent();
    const select = wrapper.find('.q-select');
    expect(select.exists()).toBe(true);
  });

  it('should have quantity input', () => {
    const wrapper = mountComponent();
    const input = wrapper.find('input[type="number"]');
    expect(input.exists()).toBe(true);
  });

  it('should have generate button', () => {
    const wrapper = mountComponent();
    const button = wrapper.find('button');
    expect(button.exists()).toBe(true);
  });

  it('should initialize with default values', () => {
    const wrapper = mountComponent();
    const vm = wrapper.vm as unknown as BingoGeneratorVM;

    expect(vm.gameType).toBe(BingoTypes.BINGO_75);
    expect(vm.quantity).toBe(6);
  });

  it('should call generate when button is clicked', async () => {
    const wrapper = mountComponent();

    // Find the "Generate Cards" button specifically
    const buttons = wrapper.findAll('button');
    const generateButton = buttons.find((btn) => btn.text().includes('Generate'));

    expect(generateButton).toBeDefined();

    if (generateButton) {
      await generateButton.trigger('click');

      // Check that cards were generated by checking store state
      await wrapper.vm.$nextTick();
      const vm = wrapper.vm as unknown as BingoGeneratorVM;
      const totalCards = vm.store.cards75.length + vm.store.cards90.length;

      expect(totalCards).toBeGreaterThan(0);
    }
  });

  it('should display Bingo75 cards when type is 75', async () => {
    const wrapper = mountComponent();
    const vm = wrapper.vm as unknown as BingoGeneratorVM;

    vm.gameType = BingoTypes.BINGO_75;
    vm.quantity = 2;
    vm.generate();

    await wrapper.vm.$nextTick();

    const cards75 = wrapper.findAllComponents(BingoCard75);
    expect(cards75.length).toBeGreaterThan(0);
  });

  it('should display Bingo90 cards when type is 90', async () => {
    const wrapper = mountComponent();
    const vm = wrapper.vm as unknown as BingoGeneratorVM;

    vm.gameType = BingoTypes.BINGO_90;
    vm.quantity = 2;
    vm.generate();

    await wrapper.vm.$nextTick();

    const cards90 = wrapper.findAllComponents(BingoCard90);
    expect(cards90.length).toBeGreaterThan(0);
  });

  it('should have print button', () => {
    const wrapper = mountComponent();
    const buttons = wrapper.findAll('button');

    const printButton = buttons.find((btn) => btn.text().includes('Print'));
    expect(printButton).toBeDefined();
  });

  it('should call window.print when print button is clicked', async () => {
    const wrapper = mountComponent();
    const vm = wrapper.vm as unknown as BingoGeneratorVM;

    // Mock window.print
    window.print = vi.fn();
    const printSpy = window.print as ReturnType<typeof vi.fn>;

    // Generate some cards first
    vm.gameType = BingoTypes.BINGO_75;
    vm.quantity = 2;
    vm.generate();

    await wrapper.vm.$nextTick();

    // Find and click print button
    vm.printCards();

    expect(printSpy).toHaveBeenCalled();
  });

  it('should clear cards when switching game types', async () => {
    const wrapper = mountComponent();
    const vm = wrapper.vm as unknown as BingoGeneratorVM;

    // Generate type 75
    vm.gameType = BingoTypes.BINGO_75;
    vm.quantity = 2;
    vm.generate();
    await wrapper.vm.$nextTick();

    // Switch to type 90
    vm.gameType = BingoTypes.BINGO_90;
    vm.quantity = 2;
    vm.generate();
    await wrapper.vm.$nextTick();

    const cards75 = wrapper.findAllComponents(BingoCard75);
    const cards90 = wrapper.findAllComponents(BingoCard90);

    expect(cards75.length).toBe(0);
    expect(cards90.length).toBeGreaterThan(0);
  });

  it('should have print grid classes after generating cards', async () => {
    const wrapper = mountComponent();
    const vm = wrapper.vm as unknown as BingoGeneratorVM;

    // Generate cards
    vm.generate();
    await wrapper.vm.$nextTick();

    const printGrid75 = wrapper.find('.print-grid-75');
    const printGrid90 = wrapper.find('.print-grid-90');

    // At least one should exist after generating
    expect(printGrid75.exists() || printGrid90.exists()).toBe(true);
  });

  it('should have no-print class on controls', () => {
    const wrapper = mountComponent();
    const controls = wrapper.find('.controls');

    expect(controls.classes()).toContain('no-print');
  });
});
